### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pierreozoux** [Boavizta/environmental-footprint-data#40]
Hi and thanks for sharing this project :)

It is currently without license, so it would be difficult for people to contribute to it.

There is this sentence in the README:
```
This data can be freely used for any purpose including without using Boavizta's methodology.
```

Then I'd advise you to use a creative common public license. If you agree, I can make the PR.

Thanks and have a nice day!

**Comment by pierreozoux** [comment]
Not an expert either :) I asked: https://twitter.com/pierreozoux/status/1455106080091090944 wait&see!

**Comment by Enro** [comment]
In France there is no intellectual property protection on a particular piece of data (e.g. the value of variable X for hardware item Y) but there are two types of protection for databases: sui generis database rights and copyright (see https://europa.eu/youreurope/business/running-business/intellectual-property/database-protection/index_en.htm). Copyright protects the structure where this is original (i.e. creative). Database rights protect the contents of a database (it does not have to be original but there needs to have been a substantial investment in obtaining, verifying or presenting the data).

So, here are the questions you need to ask yourselves:
- is the database structure original?
- was the content obtained through a substantial investment (financial, material and/or human)?

If the answer to both questions is yes, this means that you have created a novel database that is not a mere derivation of existing databases, therefore it is eligible to a licence (preferably ODbL rather than Creative Commons, which was not meant for tabular data).

**Comment by AirLoren** [comment]
Thanks a lot @Enro for these clarifications.
I think we could answer yes to both questions because : 
- the database has been structured and will evolve according to our needs
- we spent substantial time to identify sources and to develop parsers to collect the data from several type of sources

Then I think you're right and we will license it as ODBL.
